import {
  Activity,
  Bell,
  Building2,
  CalendarPlus,
  ClipboardList,
  CreditCard,
  FileBarChart,
  Fingerprint,
  Gauge,
  Landmark,
  LayoutDashboard,
  MapPinned,
  QrCode,
  RadioTower,
  ReceiptText,
  ScanLine,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Ticket,
  Users,
  Wallet,
} from "lucide-react";
import type { AuditEvent, EventItem, Metric, NavItem, TicketRow } from "@/types/gatepass";

export const publicNav = [
  { href: "/explore", label: "Explore" },
  { href: "/parties", label: "Parties" },
  { href: "/concerts", label: "Concerts" },
  { href: "/hostel-gate-pass", label: "Hostel Gate Pass" },
  { href: "/gatepass", label: "Gatepass" },
];

export const categoryRail = [
  "For You",
  "Parties",
  "Concerts",
  "Hostel Gate Pass",
  "Workshops",
  "Dining",
  "Gatepass",
  "Night Out Passes",
];

export const events: EventItem[] = [
  {
    slug: "velvet-rooftop-evening",
    title: "Velvet Rooftop Evening",
    category: "Luxury evenings",
    theme: "luxury",
    date: "Fri, 31 May",
    time: "8:00 PM",
    city: "Mumbai",
    venue: "The Ivory Terrace",
    price: "Rs 1,499",
    status: "Few tables left",
    image: "/corporate.avif",
    organizer: "GatePass Concierge",
    badges: ["Invite list", "QR entry"],
  },
  {
    slug: "midnight-frequency",
    title: "Midnight Frequency",
    category: "Parties",
    theme: "party",
    date: "Sat, 1 Jun",
    time: "10:30 PM",
    city: "Bengaluru",
    venue: "Warehouse 19",
    price: "Rs 899",
    status: "Live now",
    image: "/boilerroom/sugga.jpg",
    organizer: "Bassline Social",
    badges: ["DJ night", "Fast scan"],
  },
  {
    slug: "afterglow-arena-live",
    title: "Afterglow Arena Live",
    category: "Concerts",
    theme: "concert",
    date: "Sun, 2 Jun",
    time: "7:00 PM",
    city: "Delhi",
    venue: "North Stage",
    price: "Rs 1,250",
    status: "Selling fast",
    image: "/boilerroom/rossi-boilerroom.jpg",
    organizer: "Northstar Music",
    badges: ["Tiered tickets", "Crowd control"],
  },
  {
    slug: "campus-storm-live",
    title: "Campus Storm Live",
    category: "Concerts",
    theme: "concert",
    date: "Wed, 5 Jun",
    time: "11:00 AM",
    city: "Pune",
    venue: "Sinhgad Main Ground",
    price: "Rs 299",
    status: "Student pass open",
    image: "/boilerroom/sheral-celan.jpg",
    organizer: "Student Council",
    badges: ["Sponsor pass", "Volunteer gate"],
  },
  {
    slug: "hostel-weekend-exit-pass",
    title: "Hostel Weekend Exit Pass",
    category: "Hostel gate pass",
    theme: "hostel",
    date: "Sun, 9 Jun",
    time: "6:00 PM",
    city: "Goa",
    venue: "Seaside Hostel Gate",
    price: "Internal",
    status: "Warden approval ready",
    image: "/boilerroom/panjabi.jpg",
    organizer: "Residence Office",
    badges: ["Parent approval", "Return window", "Guard scan"],
  },
  {
    slug: "ai-founder-workshop",
    title: "AI Founder Workshop",
    category: "Workshops",
    theme: "workshop",
    date: "Sat, 8 Jun",
    time: "2:00 PM",
    city: "Hyderabad",
    venue: "Founders Room",
    price: "Rs 499",
    status: "Certificate included",
    image: "/app-event-page.jpg",
    organizer: "Build Club",
    badges: ["Paid workshop", "Email ticket"],
  },
  {
    slug: "hostel-night-out-pass",
    title: "Hostel Night-Out Pass",
    category: "Private gatepass systems",
    theme: "secure",
    date: "Today",
    time: "Active window",
    city: "Jaipur",
    venue: "Ridge Hostel",
    price: "Internal",
    status: "Approval workflow",
    image: "/smartboard.jpg",
    organizer: "Ridge Admin",
    badges: ["GPS geofence", "Guard scan"],
  },
  {
    slug: "factory-shift-exit",
    title: "Factory Shift Exit",
    category: "Private gatepass systems",
    theme: "secure",
    date: "Daily",
    time: "Shift change",
    city: "Ahmedabad",
    venue: "Unit B Gate",
    price: "Workspace",
    status: "Audit ready",
    image: "/app-tickets.jpg",
    organizer: "Ops Control",
    badges: ["Exit log", "Emergency flag"],
  },
];

export const homepageSections = [
  "Tonight's energy",
  "Luxury evenings",
  "Campus concerts",
  "Concerts near you",
  "Hostel gate passes",
  "Workshops worth attending",
  "Private gatepass systems",
];

export const dashboardNav: NavItem[] = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/dashboard/events/new", label: "Events", icon: CalendarPlus },
  { href: "/dashboard/events/demo/tickets", label: "Ticketing", icon: Ticket },
  { href: "/dashboard/orders", label: "Orders", icon: ReceiptText },
  { href: "/scanner", label: "Scanner", icon: ScanLine },
  { href: "/app/gps", label: "GPS / Geofence", icon: MapPinned },
  { href: "/dashboard/control-room", label: "Live Control Room", icon: RadioTower },
  { href: "/dashboard/gates", label: "Gates", icon: Smartphone },
  { href: "/dashboard/reports", label: "Reports", icon: FileBarChart },
  { href: "/dashboard/settlements", label: "Settlements", icon: Wallet },
  { href: "/dashboard/audit", label: "Audit Logs", icon: Fingerprint },
  { href: "/dashboard/team", label: "Team & Roles", icon: Users },
  { href: "/dashboard/communications", label: "Communications", icon: Bell },
  { href: "/dashboard/fraud", label: "Anti-Fraud", icon: ShieldAlert },
  { href: "/dashboard/offline", label: "Offline Mode", icon: Activity },
  { href: "/dashboard/settings", label: "Settings", icon: Settings },
  { href: "/dashboard/architecture", label: "Architecture", icon: Building2 },
];

export const metrics: Metric[] = [
  { label: "Total Events", value: "128", delta: "+14 this month", tone: "success" },
  { label: "Active Events", value: "18", delta: "6 live today", tone: "success" },
  { label: "Tickets Sold", value: "24,680", delta: "+18%", tone: "success" },
  { label: "Checked In", value: "18,904", delta: "76.6%", tone: "neutral" },
  { label: "Manual Tickets", value: "412", delta: "Tagged", tone: "manual" },
  { label: "Complimentary", value: "286", delta: "Sponsor + staff", tone: "complimentary" },
  { label: "Gross Sales", value: "Rs 42.8L", delta: "+9.4%", tone: "success" },
  { label: "Net Settlement", value: "Rs 38.1L", delta: "T+2 payout", tone: "success" },
  { label: "Pending Refunds", value: "31", delta: "Rs 18,420", tone: "warning" },
  { label: "Invalid Attempts", value: "19", delta: "Gate blocked", tone: "danger" },
  { label: "GPS Alerts", value: "07", delta: "Outside geofence", tone: "warning" },
  { label: "Duplicate Scans", value: "12", delta: "Blocked", tone: "danger" },
];

export const revenueData = [
  { day: "Mon", sales: 42000, checkins: 420 },
  { day: "Tue", sales: 68000, checkins: 640 },
  { day: "Wed", sales: 52000, checkins: 590 },
  { day: "Thu", sales: 91000, checkins: 820 },
  { day: "Fri", sales: 124000, checkins: 1096 },
  { day: "Sat", sales: 148000, checkins: 1280 },
  { day: "Sun", sales: 116000, checkins: 990 },
];

export const ticketRows: TicketRow[] = [
  {
    id: "TCK-8F42",
    eventId: "EVT-MIDNIGHT",
    category: "VIP",
    buyer: "Aarav Mehta",
    attendee: "Aarav Mehta",
    contact: "aarav@gatepass.test",
    qrStatus: "Signed token",
    paymentId: "PAY-9912",
    status: "issued",
    scanStatus: "checked_in",
    scanTime: "6:42 PM",
    gate: "Main Gate / Pixel 7",
    refund: "none",
  },
  {
    id: "TCK-92AA",
    eventId: "EVT-CAMPUS",
    category: "Student",
    buyer: "Nisha Rao",
    attendee: "Nisha Rao",
    contact: "nisha@gatepass.test",
    qrStatus: "Opaque token",
    paymentId: "MANUAL-CASH",
    status: "issued",
    scanStatus: "unused",
    scanTime: "-",
    gate: "-",
    refund: "none",
  },
  {
    id: "TCK-11DF",
    eventId: "EVT-HOSTEL",
    category: "Night Out Pass",
    buyer: "Kabir Sethi",
    attendee: "Kabir Sethi",
    contact: "kabir@gatepass.test",
    qrStatus: "Signed token",
    paymentId: "PAY-9920",
    status: "refunded",
    scanStatus: "blocked",
    scanTime: "Attempt 7:01 PM",
    gate: "East Gate",
    refund: "refund invalidated ticket",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    actor: "Maya Owner",
    organization: "Bassline Social",
    event: "Midnight Frequency",
    action: "Ticket scanned",
    entityType: "Ticket",
    entityId: "TCK-8F42",
    oldValue: "issued",
    newValue: "checked_in",
    timestamp: "Today 6:42 PM",
    device: "Main Gate / Pixel 7 / 103.44.1.2",
  },
  {
    actor: "Rohan Gate Staff",
    organization: "Student Council",
    event: "Campus Storm Live",
    action: "Duplicate scan attempted",
    entityType: "ScanLog",
    entityId: "SCN-4410",
    oldValue: "first scan valid",
    newValue: "ALREADY USED",
    timestamp: "Today 6:49 PM",
    device: "North Gate / Android Web",
  },
  {
    actor: "Finance Manager",
    organization: "GatePass Concierge",
    event: "Velvet Rooftop Evening",
    action: "Payout updated",
    entityType: "Settlement",
    entityId: "SET-310",
    oldValue: "pending",
    newValue: "approved T+2",
    timestamp: "Today 5:10 PM",
    device: "Chrome / admin console",
  },
];

export const trustItems = [
  { label: "Secure QR", icon: ShieldCheck },
  { label: "Audit Logs", icon: ClipboardList },
  { label: "GPS Geofence", icon: MapPinned },
  { label: "Fast Scanner", icon: ScanLine },
  { label: "Transparent Settlement", icon: Landmark },
  { label: "Low-network Ready", icon: Gauge },
  { label: "Role Access", icon: Users },
  { label: "Payment Modes", icon: CreditCard },
  { label: "Live Ops", icon: RadioTower },
  { label: "Signed Tokens", icon: QrCode },
];

export const ticketCategories = [
  "General",
  "VIP",
  "Early Bird",
  "Student",
  "Faculty",
  "Couple",
  "Group Pass",
  "Complimentary",
  "Sponsor Pass",
  "Volunteer Pass",
  "Food Included",
  "Night Out Pass",
  "Day Out Pass",
];
